### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mstijak** [huy-nguyen/squarify#29]
This is a very nice and useful library. I played a bit and it [works very well](https://codesandbox.io/s/4wrxwzxwr0).

Do you plan to add a license? Is this open source?

**Comment by huy-nguyen** [comment]
Sorry for the late reply. As stated in [package.json](https://github.com/huy-nguyen/squarify/blob/95e964e7418d18921c76d32beb7a96e9173482c3/package.json#L13), this package uses the MIT license.
