### ISSUE TITLE
squarify is not a function

### ISSUE THREAD

**Issue by jordan314** [huy-nguyen/squarify#40]
In the plain JS example, the line:  
`var output = squarify(data, container);`  
Gives the output:  
TypeError: squarify is not a function  
But by compiling the typescript, this seems to work:
`var output = squarify["default"](data, container);`

**Comment by huy-nguyen** [comment]
If you look at the [raw entry point](https://unpkg.com/browse/squarify@1.1.0/lib/index.js), the function `squarify` you're invoking is exposed as `exports.default`, which will likely cause the problem you encountered if you use it directly without any intermediate tooling like Babel. With TypeScript or Babel, you shouldn't need to do `squarify["default"]`. If you're using TypeScript directly (i.e. not with Babel + `@babel/preset-typescript`), have you tried setting `esModuleInterop` to `true` in `tsconfig.json`?
