### ISSUE TITLE
Squarify does not work with ie11

### ISSUE THREAD

**Issue by sumboxcar182** [huy-nguyen/squarify#79]
Hello! 

We just started to use this package and we found that there are syntax errors when running this in ie11. I've confirmed that it is the package, and it looks like the code that is being emitted is still using es6 features. I double checked the site that is listed in the readme and it suffers from the same issue we are hitting.

**Comment by huy-nguyen** [comment]
This package contains 3 build versions: untranspiled ES module (in `es` directory), untranspiled CommonJS module (in `lib`) and UMD build (in `dist`). Would transpiling the UMD build to work with IE11 be sufficient for your need?

**Comment by sumboxcar182** [comment]
Hello Huy!

Thank you so much for the quick response! So i pulled in the UMD build and gave it a shot and it's still failing. The UMD build still contains some es6 level code, including the => operator, which IE11 is having issues with.

So i wish i could just use the UMD bundle, but it seems like it's still giving me trouble

**Comment by huy-nguyen** [comment]
I'll make a new version whose UMD build is transpiled down to ES5 level.

**Comment by sumboxcar182** [comment]
I just saw this now, i cannot thank you enough for the quick fix!!
